<?php
// We need to use sessions, so you should always start sessions using the below code.
session_start();
// If the user is not logged in redirect to the login page...
?>
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styles.css?<?= filemtime('css/styles.css'); ?>">
    <link rel="stylesheet" href="css/scrollbar.css">
    <script src="js/check-password.js" defer></script>

    <title>Vandalgram | Terms of agreement</title>
</head>

<body id="body">
    <header id="">
        <a class="banner-title" href="index.php">Vandalgram</a>
    </header>
    <div class="menu-bar">
        <a href="register.php">[ < BACK ]</a>
    </div>
    <main>
        <div class="container-wrapper">
            <div class="reg-box">
                <h2>Terms of agreement</h1>
            </div>
            <div class=box>
                <div>
                    <?php
                    echo "<p>By registering to this website you agree with next conditions:</p><hr>" .
                        "<p>• All photos you upload to this website are photographed or generated by you and/or you have the rights to upload it</p>" .
                        "
 <p>• You do not take any credits or responsibility for possible vandalism
                        
 caught in the photo, nor do you or we support any kind of vandalism,</p>" .
                        "
 <p>• We (and you) only appreciate and promote art and the culture of photos of" .
                        "
 graffiti, trains, streets...</p>" .
                        "
 <p>• Every photo can be deleted, and in that proces it acctually is deleted from" .
                        "
the server and all the data from database..</p>
<p>• We don't collect your IP address nor do we store that info.</p>
<p>• This site has no trackers, don't use cookies for any data colecting and analyising, doesn't collect your iIP or any other info besides the info you provide. Using cookies just to keep track of your logged in status.</p>
<p>• All passwords are encrypted the moment before user sends data to server and are stored completely encrypted, not even server can decrypt them. When you login, your login entry is encrypted and compared to stored encrypted password, so there is absolutely no way to recover your password, only generate new one.</p>
<p>• Absolutely no data is shared with third party.</p>
<hr><p>• This site is still in really early development stage and there is possibility that it could get hacked. In that case no sensitive data is compromised.</p>
<p>• If you find an exploit, a bug or want to point us to the security issues, feel free to contact us.</p>";
                    ?>
                </div>
            </div>


        </div>

    </main>
    <footer><?php include "components/footer.php" ?></footer>

</html>